name: Config Auto-Update

on:
  push:
    paths:
      - 'scripts/CHANNELS.md'
    branches:
      - main

jobs:
  update-configs:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to commit updated config files
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          
      - name: Process secrets securely
        run: |
          echo '${{ secrets.ENV_SECRETS }}' > env_secrets.json
          chmod 600 env_secrets.json
          
          # Mask values
          jq -r 'to_entries[] | .value' env_secrets.json | while read -r value; do
            if [ -n "$value" ]; then
              echo "::add-mask::$value"
            fi
          done
          
          # Set environment variables
          jq -r 'to_entries[] | "\(.key)=\(.value)"' env_secrets.json > env_vars.txt
          while IFS= read -r line; do
            if [ -n "$line" ]; then
              echo "$line" >> $GITHUB_ENV
            fi
          done < env_vars.txt
          
          # Clean up
          rm env_secrets.json env_vars.txt

      - name: Install dependencies
        run: npm install

      - name: Check for channel changes and update configs
        run: |
          echo "🔍 Checking for channel configuration updates needed..."
          
          # Run in dry-run mode first to see if any changes are needed
          npm run update-configs -- --dry-run > config_changes.txt 2>&1
          
          if grep -q "Found.*channel(s) to add" config_changes.txt; then
            echo "✅ Changes detected - updating configuration files"
            cat config_changes.txt
            
            # Apply the changes
            npm run update-configs
            
            # Check if any config files were actually modified
            if [ -n "$(git status --porcelain config/)" ]; then
              echo "📝 Configuration files were updated"
              echo "CONFIG_UPDATED=true" >> $GITHUB_ENV
            else
              echo "ℹ️  No configuration files needed updating"
              echo "CONFIG_UPDATED=false" >> $GITHUB_ENV
            fi
          else
            echo "ℹ️  No configuration changes needed"
            echo "CONFIG_UPDATED=false" >> $GITHUB_ENV
            cat config_changes.txt
          fi

      - name: Commit updated config files
        if: env.CONFIG_UPDATED == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Add only config files that were modified
          git add config/
          
          # Get a summary of what changed
          TIMESTAMP=$(date -u +'%Y-%m-%d %H:%M:%S UTC')
          CHANGED_FILES=$(git diff --cached --name-only | grep "^config/" | wc -l)
          
          if [ "$CHANGED_FILES" -gt 0 ]; then
            COMMIT_MSG="Auto-update configs from channel checklist changes (${CHANGED_FILES} file(s) updated) - ${TIMESTAMP}"
            git commit -m "$COMMIT_MSG"
            git push
            echo "✅ Pushed updated configuration files"
          else
            echo "ℹ️  No config files to commit"
          fi

      - name: Summary
        run: |
          if [ "$CONFIG_UPDATED" = "true" ]; then
            echo "🎉 Configuration files automatically updated based on channel checklist changes!"
            echo "📋 The following configs may have been modified:"
            git log -1 --name-only --pretty=format:"" | grep "^config/" || echo "None"
          else
            echo "✅ Channel checklist was updated but no configuration changes were needed"
          fi